from PyQt5 import QtCore, QtGui, QtWidgets
from Classes import CodeTextWidget


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(429, 488)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Connection_groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.Connection_groupBox.setGeometry(QtCore.QRect(10, 390, 411, 91))
        self.Connection_groupBox.setObjectName("Connection_groupBox")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.Connection_groupBox)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 29, 391, 51))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.Connection_horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.Connection_horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.Connection_horizontalLayout.setObjectName("Connection_horizontalLayout")
        self.Connection_lineEdit = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.Connection_lineEdit.setStyleSheet("selection-background-color: rgb(255, 0, 0);")
        self.Connection_lineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.Connection_lineEdit.setObjectName("Connection_lineEdit")
        self.Connection_horizontalLayout.addWidget(self.Connection_lineEdit)
        self.Connection_pushButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.Connection_pushButton.setEnabled(True)
        self.Connection_pushButton.setStyleSheet("")
        self.Connection_pushButton.setAutoDefault(False)
        self.Connection_pushButton.setDefault(False)
        self.Connection_pushButton.setFlat(False)
        self.Connection_pushButton.setObjectName("Connection_pushButton")
        self.Connection_horizontalLayout.addWidget(self.Connection_pushButton)
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setEnabled(True)
        self.tabWidget.setGeometry(QtCore.QRect(-1, -1, 431, 381))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setAcceptDrops(False)
        self.tabWidget.setAutoFillBackground(False)
        self.tabWidget.setStyleSheet("")
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setElideMode(QtCore.Qt.ElideNone)
        self.tabWidget.setUsesScrollButtons(False)
        self.tabWidget.setDocumentMode(False)
        self.tabWidget.setTabsClosable(False)
        self.tabWidget.setMovable(False)
        self.tabWidget.setTabBarAutoHide(False)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.Input_groupBox = QtWidgets.QGroupBox(self.tab)
        self.Input_groupBox.setGeometry(QtCore.QRect(8, 10, 411, 331))
        self.Input_groupBox.setStyleSheet("")
        self.Input_groupBox.setObjectName("Input_groupBox")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.Input_groupBox)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 30, 391, 291))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.Input_verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.Input_verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.Input_verticalLayout.setObjectName("Input_verticalLayout")
        self.Input_plainTextEdit = CodeTextWidget.Editor(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Input_plainTextEdit.sizePolicy().hasHeightForWidth())
        self.Input_plainTextEdit.setSizePolicy(sizePolicy)
        self.Input_plainTextEdit.setObjectName("Input_plainTextEdit")
        self.Input_verticalLayout.addWidget(self.Input_plainTextEdit)
        self.Format_pushButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.Format_pushButton.setObjectName("Format_pushButton")
        self.Input_verticalLayout.addWidget(self.Format_pushButton)
        self.Send_pushButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Send_pushButton.sizePolicy().hasHeightForWidth())
        self.Send_pushButton.setSizePolicy(sizePolicy)
        self.Send_pushButton.setCheckable(False)
        self.Send_pushButton.setObjectName("Send_pushButton")
        self.Input_verticalLayout.addWidget(self.Send_pushButton)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.Input_groupBox_2 = QtWidgets.QGroupBox(self.tab_2)
        self.Input_groupBox_2.setGeometry(QtCore.QRect(8, 10, 411, 331))
        self.Input_groupBox_2.setObjectName("Input_groupBox_2")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.Input_groupBox_2)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(10, 30, 391, 291))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.Input_verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.Input_verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.Input_verticalLayout_2.setObjectName("Input_verticalLayout_2")
        self.Input_plainTextEdit_2 = CodeTextWidget.Editor(self.verticalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Input_plainTextEdit_2.sizePolicy().hasHeightForWidth())
        self.Input_plainTextEdit_2.setSizePolicy(sizePolicy)
        self.Input_plainTextEdit_2.setObjectName("Input_plainTextEdit_2")
        self.Input_verticalLayout_2.addWidget(self.Input_plainTextEdit_2)
        self.Format_pushButton_2 = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.Format_pushButton_2.setObjectName("Format_pushButton_2")
        self.Input_verticalLayout_2.addWidget(self.Format_pushButton_2)
        self.Send_pushButton_2 = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Send_pushButton_2.sizePolicy().hasHeightForWidth())
        self.Send_pushButton_2.setSizePolicy(sizePolicy)
        self.Send_pushButton_2.setCheckable(False)
        self.Send_pushButton_2.setObjectName("Send_pushButton_2")
        self.Input_verticalLayout_2.addWidget(self.Send_pushButton_2)
        self.tabWidget.addTab(self.tab_2, "")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "RAM Write Sender"))
        self.Connection_groupBox.setTitle(_translate("MainWindow", "Connection"))
        self.Connection_lineEdit.setPlaceholderText(_translate("MainWindow", "Wii U IPv4"))
        self.Connection_pushButton.setText(_translate("MainWindow", "Connect"))
        self.Input_groupBox.setTitle(_translate("MainWindow", "RAM Write Input"))
        self.Format_pushButton.setText(_translate("MainWindow", "Format"))
        self.Send_pushButton.setText(_translate("MainWindow", "Send"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "RAM Write"))
        self.Input_groupBox_2.setTitle(_translate("MainWindow", "Cafe Code Input"))
        self.Format_pushButton_2.setText(_translate("MainWindow", "Format"))
        self.Send_pushButton_2.setText(_translate("MainWindow", "Send"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Cafe Code"))
